[package]
name = "extractor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "extractor"

[dependencies]
anyhow.workspace = true
bincode-next.workspace = true
clap.workspace = true
fluent-syntax.workspace = true
fluent.workspace = true
ignore.workspace = true
log.workspace = true
memchr.workspace = true
memmap2.workspace = true
rayon.workspace = true
ruff_python_ast.workspace = true
ruff_python_parser.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "extract_bench"
harness = false

[lints.rust]
dead_code = "allow"

[lints.clippy]
too_many_arguments = "allow"
