[workspace.package]
version = "0.12.0"
edition = "2024"
rust-version = "1.95"
homepage = "https://github.com/andrew000/FTL-Extract"
documentation = "https://github.com/andrew000/FTL-Extract"
repository = "https://github.com/andrew000/FTL-Extract"
authors = ["Andrew King <help@kusbot.com>"]
license = "MIT"
include = ["src/**/*.rs"]

[workspace]
resolver = "3"
members = [
    "src/check",
    "src/cli",
    "src/common",
    "src/extractor",
    "src/stub",
]

[workspace.dependencies]
# Dev dependencies
criterion = { version = "0.8.2", features = ["html_reports"] }
pretty_assertions = { version = "1.4.1" }
tempfile = { version = "3.27.0" }

# Workspace crates
check = { path = "src/check" }
cli = { path = "src/cli" }
common = { path = "src/common" }
extractor = { path = "src/extractor" }
stub = { path = "src/stub" }

# Shared dependencies
anyhow = { version = "1.0" }
bincode-next = { version = "3.1", features = ["derive"] }
clap = { version = "4.6", features = ["derive"] }
env_logger = { version = "0.11" }
fluent-syntax = { git = "https://github.com/projectfluent/fluent-rs.git", rev = "b822cfe0ac5f35099ee71d3cf6f43b7c01d5fc6d" }
ignore = { version = "0.4" }
indexmap = { version = "2.14", features = ["serde"] }
log = { version = "0.4" }
memchr = { version = "2.8" }
memmap2 = { version = "0.9" }
mimalloc = { version = "0.1" }
rayon = { version = "1.12" }
ruff_python_ast = { version = "0.0.12" }
ruff_python_parser = { version = "0.0.12" }
rustc-hash = { version = "2.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
smallvec = { version = "2.0.0-alpha.13" }
toml = { version = "1.1" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true

[profile.test]
opt-level = 0
lto = "off"
codegen-units = 128
strip = false

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
