[package]
name = "check"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "check"

[dependencies]
anyhow.workspace = true
extractor = { path = "../extractor" }
fluent-syntax.workspace = true
ignore.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
