[package]
name = "common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "common"

[dependencies]
anyhow.workspace = true
fluent-syntax.workspace = true
ignore.workspace = true
memchr.workspace = true
rustc-hash.workspace = true
tempfile.workspace = true
